name: Release Plugin
on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer

      - name: Install Composer dependencies (production)
        run: |
          composer install --no-dev --optimize-autoloader --prefer-dist

      - name: Create clean build folder
        run: |
          mkdir -p release/custom-site-functions
          rsync -av \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='.idea' \
            --exclude='release' \
            --exclude='vendor' \
            --exclude='composer.json' \
            --exclude='build.sh' \
            --exclude='composer.lock' \
            ./ \
            release/custom-site-functions/

      - name: Copy plugin-update-checker to plugin root
        run: |
          rsync -av \
            vendor/yahnis-elsts/plugin-update-checker/ \
            release/custom-site-functions/plugin-update-checker/

      - name: Create ZIP
        run: |
          cd release
          zip -r custom-site-functions.zip custom-site-functions

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/custom-site-functions.zip