name: Release Plugin
on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

        with:
          php-version: "8.2"
          tools: composer

      - name: Install Composer dependencies (production)
        run: |
          composer install --no-dev --optimize-autoloader --prefer-dist

      - name: Create clean build folder
        run: |
          mkdir release
          rsync -av \
            acf-custom-fields-plugin/ \
            release/acf-custom-fields-plugin/

      - name: Copy vendor into plugin
        run: |
          rsync -av vendor release/acf-custom-fields-plugin/

      - name: Remove dev-only files
        run: |
          rm -f release/custom-site-functions/composer.json
          rm -f release/custom-site-functions/composer.lock

      - name: Create ZIP
        run: |
          cd release
          zip -r custom-site-functions.zip acf-custom-fields-plugin

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/custom-site-functions.zip